### ISSUE TITLE
Is that whole course?

### ISSUE THREAD

**Issue by zvookiejoo** [openmainframeproject/cobol-programming-course#46]
I would like to say thanks to you! It were so nice to touch mainframes and history of programming languages.

But, should I wait for appearance of more complex tasks, that make me closer to mainframes & COBOL reality?

**Comment by sccosel** [comment]
Check this out: https://developer.ibm.com/technologies/cobol/

**Comment by sccosel** [comment]
@zvookiejoo and All:
Have you tried making GROSS-PAY display like this: $1,234.56?  Give that a whirl.
Make the number 123 display as $123.00.  Make ZERO display as $0.00.
1) The SEARCH verb (sequential and binary variations) is used quite often in Cobol programs.  Interview question: "Explain table handling in Cobol."  Hint: Use the SEARCH verb and the REDEFINES clause in the DATA DIVISION.
2) Study 88 level items in the DATA DIVISION, what they are and how to use them. Also involves the SET verb.
3) INSPECT and INSPECT REPLACING (older IBM pre-COBOL II compilers used EXAMINE), is used quite often.
4) Making 2 fields print on the same line together (e.g. first and last name) without blank space in between, is also a concept.  Hint:  use the STRING verb.
5) Study the UNSTRING verb.
6) Look at the COBOL Language Reference Manual, and study all the available reserved words in Chapter 20. Learn their purpose and what they do. IBM Cobol Language Reference Manual v6.3 http://publibfp.boulder.ibm.com/epubs/pdf/igy6lr30.pdf.
7) Study the Cobol intrinic functions available, Chapter 21 of the same manual.
8) Don't ever use the GO TO verb, no need to use it.
9) Don't ever use the ALTER (GO TO) verb, and pray you don't run into any programs that do.
10) Avoid tying your program up in "NOT"s (for non-English speakers, this is a play on words; the word "not" vs. the word "knot"), i.e. don't ever use NOT in conditional statements, or at least very sparingly.  You can use CONTINUE (nop in other languages) to accomplish the same thing with positive, rather than negative logic.
11)  Study the case structure verb, EVALUATE, EVALUATE TRUE, and EVALUATE variable-name.  Be sure to use WHEN OTHER as a final condition in an EVALUATE statement.
12) Next, you should familiarize yourself with JCL.  Study the examples.  z/OS MVS JCL Reference v2r3, https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3SA231385/$file/ieab600_v2r3.pdf  13) Then after all that, study the DFSORT manual (and also ICETOOL).  Sorting (using DFSORT or a 3rd party software product, e.g. SYNCSORT is very common) is heavily used in commercial (real world) environments. If you only learn one general use utility, this is the one to learn.  DFSORT Application Programming Guide, v2r3, https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3sc236878/$file/icea100_v2r3.pdf  Most of you here probably already know how to program in other languages better than I.  What will be most beneficial to you, is to learn many of the unique things about Cobol (the above items are a start), and understand why Cobol is well suited to process transactions, i.e. processing files containing lines of data to process, whether to update another output "flat" file or a database.  Lots of things to study, learn and try.  And ask questions in this forum for the benefit of all, perhaps to motivate others here to learn another thing or two that they didn't already know!  Good luck!

**Comment by sccosel** [comment]
@zvookiejoo and All:
Have you tried making GROSS-PAY display like this: $1,234.56?  Give that a whirl.
Make the number 123 display as $123.00.  Make ZERO display as $0.00.
1) The SEARCH verb (sequential and binary variations) is used quite often in Cobol programs.  Interview question: "Explain table handling in Cobol."  Hint: Use the SEARCH verb and the REDEFINES clause in the DATA DIVISION.
2) Study 88 level items in the DATA DIVISION, what they are and how to use them. Also involves the SET verb.
3) INSPECT and INSPECT REPLACING (older IBM pre-COBOL II compilers used EXAMINE), is used quite often.
4) Making 2 fields print on the same line together (e.g. first and last name) without blank space in between, is also a concept.  Hint:  use the STRING verb.
5) Study the UNSTRING verb.
6) Look at the COBOL Language Reference Manual, and study all the available reserved words in Chapter 20. Learn their purpose and what they do. IBM Cobol Language Reference Manual v6.3 http://publibfp.boulder.ibm.com/epubs/pdf/igy6lr30.pdf.
7) Study the Cobol intrinic functions available, Chapter 21 of the same manual.
8) Don't ever use the GO TO verb, no need to use it.
9) Don't ever use the ALTER (GO TO) verb, and pray you don't run into any programs that do.
10) Avoid tying your program up in "NOT"s (for non-English speakers, this is a play on words; the word "not" vs. the word "knot"), i.e. don't ever use NOT in conditional statements, or at least very sparingly.  You can use CONTINUE (nop in other languages) to accomplish the same thing with positive, rather than negative logic.
11)  Study the case structure verb, EVALUATE, EVALUATE TRUE, and EVALUATE variable-name.  Be sure to use WHEN OTHER as a final condition in an EVALUATE statement.
12) Next, you should familiarize yourself with JCL.  Study the examples.  z/OS MVS JCL Reference v2r3, https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3SA231385/$file/ieab600_v2r3.pdf  13) Then after all that, study the DFSORT manual (and also ICETOOL).  Sorting (using DFSORT or a 3rd party software product, e.g. SYNCSORT is very common) is heavily used in commercial (real world) environments. If you only learn one general use utility, this is the one to learn.  DFSORT Application Programming Guide, v2r3, https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3sc236878/$file/icea100_v2r3.pdf  Most of you here probably already know how to program in other languages better than I.  What will be most beneficial to you, is to learn many of the unique things about Cobol (the above items are a start), and understand why Cobol is well suited to process transactions, i.e. processing files containing lines of data to process, whether to update another output "flat" file or a database.  Lots of things to study, learn and try.  And ask questions in this forum for the benefit of all, perhaps to motivate others here to learn another thing or two that they didn't already know!  Good luck!

**Comment by sccosel** [comment]
Here's a JCL primer on IBM utilities that some of you might find helpful.  Note that with all sample JCL found on the Internet (or anywhere you find sample JCL), the JOBCARD needs to be customized to run on your unique system.  Try to understand what each sample JCL does, and what each of the parameters mean before you try running it.  Also, the VOL=SER=xxxxxx parameter will be different as well as the UNIT=xxxxxx parameters.  All units are basically (some variation of) 3390 these days!  Real IBM hardware hasn't used 3330's, 3350's and 3380's devices in years.  The JCL at this link may be dated, but the basic concepts are still relevant today. http://www.bsp-gmbh.com/turnkey/cookbook/utilmvs.html

**Comment by zvookiejoo** [comment]
When I had no access to mainframe, i had to install Hercules and tk4- to my PC. There was very old version of COBOL compiler and I had to rewrite CBL0001.
`        IDENTIFICATION DIVISION.
        PROGRAM-ID. CBL001.
        ENVIRONMENT DIVISION.
        INPUT-OUTPUT SECTION.
        FILE-CONTROL.
            SELECT PRINT-LINE ASSIGN TO UT-S-PRTLINE.
            SELECT ACCT-REC ASSIGN TO DA-S-ACCTREC.
        DATA DIVISION.
        FILE SECTION.
        FD PRINT-LINE
            RECORDING MODE F
            LABEL RECORDS ARE OMITTED.
        01 PRINT-REC.
            05 ACCT-NO-O PIC X(8).
            05 ACCT-LIMIT-O PIC $$,$$$,$$9.99.
            05 ACCT-BALANCE-O PIC $$,$$$,$$9.99.
            05 LAST-NAME-O PIC X(20).
            05 FIRST-NAME-O PIC X(15).
            05 COMMENTS-O PIC X(50).
        FD ACCT-REC
            RECORDING MODE F
            RECORD CONTAINS 170 CHARACTERS
            BLOCK CONTAINS 5 RECORDS
            LABEL RECORDS ARE STANDARD
            DATA RECORD IS ACCT-FIELDS.
        01 ACCT-FIELDS.
            05 ACCT-NO PIC X(8).
            05 ACCT-LIMIT PIC S9(7)V99 COMP-3.
            05 ACCT-BALANCE PIC S9(7)V99 COMP-3.
            05 LAST-NAME PIC X(20).
            05 FIRST-NAME PIC X(15).
            05 CLIENT-ADDR.
              10 STREET-ADDR PIC X(25).
              10 CITY-COUNTY PIC X(20).
              10 USA-STATE PIC X(15).
            05 RESERVED PIC X(7).
            05 COMMENTS PIC X(50).
        WORKING-STORAGE SECTION.
        01 FLAGS.
            05 LASTREC PIC X VALUE SPACE.
        PROCEDURE DIVISION.
        OPEN-FILES.
            OPEN INPUT ACCT-REC.
            OPEN OUTPUT PRINT-LINE.
        READ-NEXT-RECORD.
            PERFORM READ-RECORD UNTIL LASTREC = 'Y'.
        END-READ-NEXT.
        CLOSE-STOP.
            CLOSE ACCT-REC.
            CLOSE PRINT-LINE.
            STOP RUN.
        READ-RECORD.
            READ ACCT-REC AT END MOVE 'Y' TO LASTREC.
            PERFORM WRITE-RECORD.
        END-READ.
        WRITE-RECORD.
            MOVE ACCT-NO TO ACCT-NO-O.
            MOVE ACCT-LIMIT TO ACCT-LIMIT-O.
            MOVE ACCT-BALANCE TO ACCT-BALANCE-O.
            MOVE LAST-NAME TO LAST-NAME-O.
            MOVE FIRST-NAME TO FIRST-NAME-O.
            MOVE COMMENTS TO COMMENTS-O.
            WRITE PRINT-REC.
        END-WRITE.`

And make my own CBL0001J.

`//HERC01CO JOB (1),'CBL001',CLASS=A,MSGCLASS=H,MSGLEVEL=(1,1)
//COB      EXEC COBUCLG,REGION=1024K
//SYSPUNCH DD DUMMY
//SYSLIB   DD DSNAME=SYS1.COBLIB,DISP=SHR
//COB.SYSIN DD DISP=SHR,DSN=ZJO.STUDY.PGM(CBL001)
//LKED.SYSLIB DD DISP=SHR,DSNAME=SYS1.COBLIB
//            DD DISP=SHR,DSNAME=SYS1.LINKLIB
//GO.SYSPRINT DD SYSOUT=*
//GO.PRTLINE  DD SYSOUT=*
//GO.ACCTREC  DD DISP=SHR,DSN=ZJO.STUDY.DATA
`

**Comment by paulnewt** [comment]
From recent article ---- But just because the technology is several decades old doesn't necessarily mean it's out of date. Because developers have continuously improved COBOL, many companies and government agencies opt to stick with it rather than switch over to newer options, according to Bill Hinshaw, founder and CEO of Cobol Cowboys, a company that connects experienced COBOL programmers with employers.
"I tell people, it's like if you're riding a bicycle, you hop off of it, and you jump on a Harley Davidson,” Hinshaw says. “That's the type of change you will see from the COBOL mainframes 60 years ago to what it is today. It's not even comparable.”

**Comment by paulnewt** [comment]
today's COBOL is significantly advanced - which includes features/functions in addition to performance .... those features/functions are not meant for the bicycle COBOL

**Comment by jellypuno** [comment]
@zvookiejoo I have a COBOL challenge. maybe you want to give it a try: https://medium.com/@jessielaine.punongbayan/cobol-challenge-covid-19-reports-ee03a946bd23

**Comment by MrGmaw** [comment]
> @zvookiejoo I have a COBOL challenge. maybe you want to give it a try: https://medium.com/@jessielaine.punongbayan/cobol-challenge-covid-19-reports-ee03a946bd23

Cannot acces to https://covid19api.com/ nor https://api.covid19api.com/summar nor https://api.covid19api.com/summary

**Comment by jellypuno** [comment]
> Cannot acces to https://covid19api.com/ nor https://api.covid19api.com/summar nor https://api.covid19api.com/summary

Thank you for letting me know. It seems like the link was broken. I updated it and let me know if you can access it now.

**Comment by MrGmaw** [comment]
> @zvookiejoo I have a COBOL challenge. maybe you want to give it a try: https://medium.com/@jessielaine.punongbayan/cobol-challenge-covid-19-reports-ee03a946bd23

Cannot acces to https://covid19api.com/ nor https://api.covid19api.com/summar nor https://api.covid19api.com/summary

> > Cannot acces to https://covid19api.com/ nor https://api.covid19api.com/summar nor https://api.covid19api.com/summary
> 
> @MrGmaw Thank you for letting me know. It seems like the link was broken. I updated it and let me know if you can access it now.

Web site ok. But not the summary one. https://api.covid19api.com/summary

**Comment by jellypuno** [comment]
@MrGmaw You should be able to see this:

![Capture](https://user-images.githubusercontent.com/45042840/80096870-991c0780-856a-11ea-8d94-3a961374d26f.PNG)

If not, maybe you have a firewall or something that prevents you from getting it. I could send the file, if you want. I think I can upload it here.

**Comment by MrGmaw** [comment]
> @MrGmaw You should be able to see this:
> 
> ![Capture](https://user-images.githubusercontent.com/45042840/80096870-991c0780-856a-11ea-8d94-3a961374d26f.PNG)
> 
> If not, maybe you have a firewall or something that prevents you from getting it. I could send the file, if you want. I think I can upload it here.

Yes! You're right. Kids DNS restrict it. IT's ok now. Thank you

**Comment by zvookiejoo** [comment]
> 
> 
> @zvookiejoo I have a COBOL challenge. maybe you want to give it a try: https://medium.com/@jessielaine.punongbayan/cobol-challenge-covid-19-reports-ee03a946bd23

I've done table-formatted output.

Code: https://github.com/zvookiejoo/cobol/blob/master/covid
JCL: https://github.com/zvookiejoo/cobol/blob/master/COVIDJ

There is a problem with CBL dataset allocated to me: record length is limited to 80 characters. When I upload the new member - CSV lines are truncated and parts of data are lost. Also, some country names in this data set have commas - following record fields are shifted.

Making a HTTP request directly to API and processing of received JSON would be the best way to.

IBM Enterprise COBOL have JSON PARSE statement, but I not found the way to make HTTP Request. Or, may be, there is some program or JCL function, that could receive data from web-server and transfer it to COBOL program input?

**Comment by jellypuno** [comment]
@zvookiejoo Thank you for trying out the exercise! I hope you had fun. :)

> There is a problem with CBL dataset allocated to me: record length is limited to 80 characters. When I upload the new member - CSV lines are truncated and parts of data are lost. Also, some country names in this data set have commas - following record fields are shifted.

I agree. CSV has a different length and I guess I should have said allocate a sequential dataset and upload it to mainframe. I didn't mean to upload it the *.CBL dataset. Thank you for the clarification. I will keep this in mind.

> Making a HTTP request directly to API and processing of received JSON would be the best way to.

I agree. I decided to write a different program to do this. It is a combination of Typescript and Zowe CLI.

IBM Enterprise COBOL have JSON PARSE statement, but I not found the way to make HTTP Request. Or, may be, there is some program or JCL function, that could receive data from web-server and transfer it to COBOL program input?

> z/OS CONNECT is the only thing that I know that can process API request. And I haven't tried it.

**Comment by MrGmaw** [comment]
@jellypuno Glad because I've accomplish this challenge. I've learned some important features about zowe as well as to handle data-items and to understand report layouts in COBOL. It was a very good way to practice what I've learned until now. Hope there will be an advanced COBOL course.

**Comment by sccosel** [comment]
@MrGmaw Have you explored this yet: https://github.com/openmainframeproject/cobol-programming-course/issues/46

**Comment by MrGmaw** [comment]
> @MrGmaw Have you explored this yet: #46?

Yes, indeed I have some comments here in issue #46. Some particular comment?

**Comment by sccosel** [comment]
@MrGmaw, Yes, look at the third comment, my comment to "zvookiejoo".  A small challenge and then a long list of things to study and try.

**Comment by MrGmaw** [comment]
> 
> 
> @MrGmaw, Yes, look at the third comment, my comment to "zvookiejoo". A small challenge and then a long list of things to study and try.
Yes, I've done almost all of it. What I didn't read is the pdf about DFSORT and ICETOOL. I'll do it. 
I've been testing indexed files, recover a keyed record, deleting, rewriting, controling file status regarding error code, reading about zowe and Db2 to figure it out how to implement Db2 access.
